[package]
name = "aura_clothing_advisor"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
axum-server = "0.7.2"
tower-http = { version = "0.6.2", features = ["cors"] }



